### ISSUE TITLE
compiling error in stream_producer.h after Commit 87808c5

### ISSUE THREAD

**Issue by Colug0** [SignalK/SensESP#959]
today I got the following error when I tried to compile my halmet firmware, I think it is related to the changes in Commit 87808c5

```
pio/libdeps/halmet/SensESP/src/sensesp/system/stream_producer.h: In member function 'void sensesp::StreamLineProducer::receive_line()':
.pio/libdeps/halmet/SensESP/src/sensesp/system/stream_producer.h:63:20: error: cannot convert 'std::unique_ptr<char []>' to 'const String&'
   63 |         this->emit(buf_);
      |                    ^~~~
      |                    |
      |                    std::unique_ptr<char []>

```

**Comment by mairas** [comment]
Thanks for the report. This is fixed in **v3.4.0**.

The bug was introduced in 87808c5 (shipped in v3.3.0): `StreamLineProducer::receive_line()` passed the `std::unique_ptr<char[]>` buffer straight to `emit()`, which expects a `const String&`. The fix (bb7b8624f) constructs a `String` from the buffer first:

```cpp
this->emit(String(buf_.get()));
```

v3.4.0 (released 2026-06-03) is the current latest release and includes the fix. Bump your dependency to pull it in — e.g. in `platformio.ini`:

```ini
lib_deps =
    SignalK/SensESP @ ^3.4.0
```

then clear the cached copy so the new version is fetched:

```
pio pkg update
```

Closing as fixed in v3.4.0 — please reopen if you still see it after upgrading.
